apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: example-websockets
spec:
  template:
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
